#!/bin/bash
#$ -S /bin/bash


CMDNAME="FRACTAL"
#setting defalt parameter

MAX_ITERATION=5             #Integer
SUBSAMPLE_SIZE=10          #Integer
INFILE="unspecified"        #Absolute Path of .fa file
NAME="FRACTALout"           #Experiment No.
CODE_DIR=`dirname $0`       #Absolute path of FRACTAL directory
OUT_DIR="`pwd`"             #output dir should be ${OUT_DIR}/${NAME}
SOFTWARE="unspecified"      #Absolute Path of the executable file for lineage reconstruction
THRESHOLD=10
ROOTING="Origin"
NUM_OF_JOBS=1
TREE=raxmlMP
THREADNUM=1
COLOR="FALSE"
REMOVE_INTERMEDIATES=TRUE
OPTION="" # option of tree reconstruction software
SEED=0
MODEL="GTRCAT"
QSUB_OPTION="" # option of qsub
INIT_QSUB_OPTION="" # option of qsub
ASSEMBLY_QSUB_OPTION=""
JOB_NAME="FRACTAL"
PLACEMENT_METHOD="ML"
EXTRACTION_SIZE=10000000000
ALIGNED="aligned"
LIMITATION=10000
FASTA_or_EDIT="fa"
CAREFUL_PLACEMENT=1
GZIP_INTERMEDIATE="FALSE"
SEQ_NUM_FILE="unspecified"
benchmark="TRUE"
ALIGNMENT_FREQUENCY=0.5

function version {
  echo "######## FRACTAL v2.6.2 ########"
}

function usage {
    cat <<EOF
FRACTAL is a tool for lineage estimation from massive number of DNA sequences.

Usage:
    FRACTAL.sh
    [-v] [-h] [-i input_file] [-o output_file_path] [-f output_file_name]
    [-m method] [-a "options"] [-s script_file_name] [-k sequence_number]
    [-u] [-w alignment_frequency] [-b model_name] 
    [-p placement_method] [-x iteration_number] [-t sequence_number]
    [-d job_number] [-c thread_number] [-e] [-r integer] [-n file_path] [-E] 
    [-O qsub_option] [-I first_qsub_option] [-A last_qsub_option] [-j job_name] 
    [-l iteration_upper_limit] [-g]

Options:
    -v
      Print FRACTAL version. Ignore all the other parameters.
    -h
      Print the usage of FRACTAL. Ignore all the other parameters.
    -i <String>
      Input FASTA file
    -o <String>
      Output directory path. Default: current working directory
    -f <String>
      Output file name. Default: FRACTALout
    -m <String, Permissible values: ‘raxmlMP’, ‘rapidnjNJ’ and ‘fasttreeML’>
      Method to reconstruct lineage tree in each iteration cycle. Default: raxmlMP
        When -s is specified, this option will be ignored.
    -a "<String>"
      Options for the software tool selected by -m
    -s <String>
      File name of a shell script for a user-defined lineage reconstruction tool 
    -k <Integer>
      Number of sequences for the subsampling procedure. Default: 10
    -z <Integer>
      Number of leaves randomly extracted from sample trees for the phylogenetic placement.
        Default: same as the value specified by -k
    -u
      Reconstuct a lineage from unaligned sequences.
    -w <float>
      Fold-change threshold that determines the timing to update the MSA and the plus-one 
        alignment result. This option is valid only when -u is specified. Default: 0.5
    -b <String>
      Substitution model of RAxML for phylogenetic placement. Default: GTRCAT
    -p <String, Permissible values: ‘ML’, ‘MP’>
      Method of phylogenetic placement. Default: ML
    -x <Integer>
      Threshold for the maximum number of retrial iterations in the subsampling process
    -t <Integer>
      Threshold number of input sequences to switch to direct lineage tree reconstruction 
        in each iteration cycle. Default: 10
    -d <Integer>
      Maximum number of jobs permissible for distributed computing.
        Default: 1 (no distributed computing)
    -c <Integer>
      Number of threads for the subsample tree reconstruction and the phylogenetic placement
        in each iteration cycle. Default: 1
    -e
      Output intermediate files
    -r <Integer>
      Seed number for generation of random values. Default: 0
    -E 
      Reconstruct a lineage from mutation lists of the input sequences. 
      Currently, this option can be specified only with "-p MP -d 1" and without "-g".
    -O "<String>"
      Options for qsub. Default: ""
        example:  -O "-pe def_slot 4 -l s_vmem=16G -l mem_req=16G" 
    -I "<String>"
      Options specified for the first qsub job. Default: Same as the string specified by -O
    -A "<String>"
      Options specified for the last qsub job (tree assembly). 
        Default: Same as the string specified by -O
    -j "<String>"
      Common name header of the jobs distributed by FRACTAL. Default: "FRACTAL"
    -l <Integer>
      Maximum number of FRACTAL iterations. Default: 10000
    -g 
      gzip intermediate files.
EOF
}

# read argument
while getopts i:o:f:s:a:k:w:b:p:P:x:t:d:c:r:n:O:I:A:j:m:l:z:vheugEB OPT
do
  case $OPT in
    "v" ) version; exit 1;;
    "h" ) version; usage; exit 1;;
    "i" ) FLG_i="TRUE" ; INFILE="$OPTARG";;
    "o" ) FLG_o="TRUE" ; OUT_DIR="$OPTARG";;
    "f" ) FLG_F="TRUE" ; NAME="$OPTARG";;
    "s" ) FLG_s="TRUE" ; SOFTWARE=`which $OPTARG`;;
    "a" ) FLG_A="TRUE" ; OPTION="$OPTARG";;
    "k" ) FLG_K="TRUE" ; SUBSAMPLE_SIZE="$OPTARG";;
    "w" ) FLG_W="TRUE" ; ALIGNMENT_FREQUENCY="$OPTARG";;
    "b" ) FLG_B="TRUE" ; MODEL="$OPTARG";;
    "p" ) FLG_P="TRUE" ; PLACEMENT_METHOD="$OPTARG";;
    "P" ) FLG_P="TRUE" ; CAREFUL_PLACEMENT="$OPTARG";;
    "x" ) FLG_X="TRUE" ; MAX_ITERATION="$OPTARG";;
    "t" ) FLG_T="TRUE" ; THRESHOLD="$OPTARG";;
    "d" ) FLG_D="TRUE" ; NUM_OF_JOBS="$OPTARG";;
    "c" ) FLG_C="TRUE" ; THREADNUM="$OPTARG";;
    "e" ) REMOVE_INTERMEDIATES="FALSE" ;;
    "r" ) FLG_R="TRUE" ; SEED="$OPTARG";;
    "n" ) FLG_N="TRUE" ; SEQ_NUM_FILE="$OPTARG";;
    "E" ) FLG_E="TRUE" ; FASTA_or_EDIT="edit";;
    "O" ) FLG_O="TRUE" ; QSUB_OPTION="$OPTARG";;
    "I" ) FLG_I="TRUE" ; INIT_QSUB_OPTION="$OPTARG";;
    "A" ) FLG_A="TRUE" ; ASSEMBLY_QSUB_OPTION="$OPTARG";;
    "j" ) FLG_j="TRUE" ; JOB_NAME="$OPTARG";;
    "m" ) FLG_m="TRUE" ; TREE="$OPTARG";;
    "u" ) FLG_u="TRUE" ; ALIGNED="unaligned";;
    "l" ) FLG_u="TRUE" ; LIMITATION="$OPTARG";;
    "z" ) FLG_z="TRUE" ; EXTRACTION_SIZE="$OPTARG";;
    "g" ) FLG_g="TRUE" ; GZIP_INTERMEDIATE="TRUE";;
    "B" ) benchmark="TRUE" ;;
    * ) usage; exit 1;;
  esac
done

# print version
version

# checking existance of directories
if [ ! -e ${INFILE} ]; then
  INFILE=`pwd`/${INFILE}
fi
if [ ! -e ${INFILE} ]; then
  echo "${INFILE} was not found" 1>&2
  exit 1
fi
echo "Input FASTA file ... OK"
if [ ! -e ${CODE_DIR} ]; then
  echo "executable FRACTAL.sh was not found" 1>&2
  exit 1
fi
echo "Code directory   ... OK"
echo "################################"

if [ "${SOFTWARE}" = "unspecified" ]; then 
    # setting tree construction software
    # ML (RAxML)
    if [ "${TREE}" = "raxmlML" ]; then
    SOFTWARE=`which raxmlHPC-SSE3`
    # NJ
    elif [ "${TREE}" = "rapidnjNJ" ]; then
    SOFTWARE=`which rapidnj`
    # MP
    elif [ "${TREE}" = "raxmlMP" ]; then
    SOFTWARE=`which raxmlHPC-SSE3`
    # ML (fasttree)
    elif [ "${TREE}" = "fasttreeML" ]; then
    SOFTWARE=`which FastTreeMP`
    # any other software
    else
    echo "exception: Tree construction method name seems wrong..."
    fi
else
    echo "Executable file used to reconstruct lineages: $SOFTWARE"
    TREE="unspecified" # when -s is specified, -m is ignored
fi

echo "Command:"
echo "$0 $*"
echo "################################"

bash ${CODE_DIR}/shell/SUPERVISE.sh ${MAX_ITERATION} ${SUBSAMPLE_SIZE} ${INFILE} ${NAME} ${CODE_DIR} ${OUT_DIR} ${THRESHOLD} ${ROOTING} ${NUM_OF_JOBS} ${TREE} ${THREADNUM} ${SOFTWARE} "${OPTION}" ${MODEL} "${QSUB_OPTION}" "${INIT_QSUB_OPTION}" "${ASSEMBLY_QSUB_OPTION}" "${SEED}" "${JOB_NAME}" ${PLACEMENT_METHOD} ${ALIGNED} ${LIMITATION} ${EXTRACTION_SIZE} ${CAREFUL_PLACEMENT} ${FASTA_or_EDIT} ${GZIP_INTERMEDIATE} ${SEQ_NUM_FILE} ${benchmark} ${ALIGNMENT_FREQUENCY}
wait

#show result
cp ${OUT_DIR}/${NAME}/final_tree/HUGE_Result.nwk ${OUT_DIR}/${NAME}.nwk
if [ ${REMOVE_INTERMEDIATES} = "TRUE" ]; then
  rm -r $OUT_DIR/$NAME
fi