#!/usr/bin/env bash
set -e

mkdir /dependencies
cd /dependencies
curl -L https://github.com/stamatak/standard-RAxML/archive/v8.2.12.tar.gz | tar xz
cd standard-RAxML-8.2.12
make -f Makefile.SSE3.gcc
rm *.o
make -f Makefile.SSE3.PTHREADS.gcc
rm *.o
cp raxmlHPC-SSE3 /bin
cp raxmlHPC-PTHREADS-SSE3 /bin

cd /dependencies
curl -LO http://www.microbesonline.org/fasttree/FastTreeMP
chmod u+x FastTreeMP
cp FastTreeMP /bin